task: deform
exp_name: anisdf_xuzhen36

train_dataset_module: lib.datasets.base_dataset
test_dataset_module: lib.datasets.base_dataset
network_module: lib.networks.deform.anisdf_network
renderer_module: lib.networks.renderer.base_renderer
trainer_module: lib.train.trainers.base_trainer
evaluator_module: lib.evaluators.base_evaluator
visualizer_module: lib.visualizers.base_visualizer

train_dataset:
    data_root: data/xuzhen36/talk
    human: xuzhen36
    ann_file: data/xuzhen36/talk/annots.npy
    split: train

test_dataset:
    data_root: data/xuzhen36/talk
    human: xuzhen36
    ann_file: data/xuzhen36/talk/annots.npy
    split: test

train:
    batch_size: 4 # ddp 8
    collator: ''
    lr: 5e-4
    weight_decay: 0.0
    epoch: 200
    scheduler:
        type: exponential
        gamma: 0.1
        decay_epochs: 200
    num_workers: 16
    sampler: RandomSampler

test:
    sampler: FrameSampler
    frame_sampler_interval: 30
    batch_size: 1
    collator: ''

ep_iter: 500
save_ep: 50
eval_ep: 50

# training options
norm_th: 0.1
dist_th: 0.1
surf_reg_th: 0.02

train_chunk_size: 4096
render_chunk_size: 4096
erode_dilate_mask: False

# rendering options
sdf_res: 6
xyz_res: 10
view_res: 4

n_samples: 64
n_rays: 1024

perturb: 1.0
bg_brightness: 0.0

# data options
ratio: 0.5
# prettier-ignore
training_view: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,]
# prettier-ignore
test_view: [17, 0, 18, 15, 1, 27, 8, 30, 4, 34, 28, 12, 9, 10, 21, 3, 25, 16, 26, 19, 6, 35, 20, 7, 24, 29]

frame_interval: 1
begin_ith_frame: 0
num_train_frame: 1600
num_eval_frame: 400
num_render_view: 256

smpl: smplh
lbs: lbs
params: params
vertices: vertices

# visualization config
voxel_size: [0.005, 0.005, 0.005]

# record options
log_interval: 1

# loss configuration
eikonal_loss_weight: 0.1
observed_eikonal_loss_weight: 0.1
resd_loss_weight: 0.01
img_loss_weight: 1.0

pose_seq_cfg:
    train_dataset_module: lib.datasets.pose_dataset
    test_dataset_module: lib.datasets.pose_dataset
    visualizer_module: lib.visualizers.pose_visualizer

    test:
        frame_sampler_interval: 1

    test_view: [0]

novel_view_cfg:
    train_dataset_module: lib.datasets.demo_dataset
    test_dataset_module: lib.datasets.demo_dataset
    visualizer_module: lib.visualizers.demo_visualizer

    test:
        frame_sampler_interval: 1

mesh_cfg:
    renderer_module: lib.networks.renderer.mesh_renderer
    train_dataset_module: lib.datasets.mesh_dataset
    test_dataset_module: lib.datasets.mesh_dataset
    evaluator_module: lib.evaluators.mesh_evaluator
    visualizer_module: lib.visualizers.mesh_visualizer

    test:
        sampler: MeshFrameSampler
        frame_sampler_interval: 100

    dist_th: 0.2
    mesh_th: 0.5
    mesh_th_to_sdf: True

sphere_tracing_cfg: # will force a sphere tracing renderer
    render_chunk_size: 1048576
    renderer_module: lib.networks.renderer.sphere_tracing_renderer

novel_light_cfg: # will use a relighting rendering to store relighting results
    renderer_module: lib.networks.renderer.novel_light_renderer
    visualizer_module: lib.visualizers.light_visualizer
